### ISSUE TITLE
Does the NetEase album->song listing work for you?

### ISSUE THREAD

**Issue by jefesaurus** [stevenyang1011/amp-awesome-music-player#1]
I've been trying and not succeeding to get the Netease album listing api to work.
There are multitudes of api's around that all do roughly the same thing:
http://music.163.com/api/album/428503?id=428503
or
http://music.163.com/api/album/428503

for example. But these give 'illegal request' exceptions.

I'm just wondering if you've managed to get the album listing api working, thanks.

**Comment by stevenyang1011** [comment]
I believe you need the right request headers like in this file in the project:
https://github.com/stevenyang1011/amp-awesome-music-player/blob/master/app/model/api.server.model.js

I have also got a couple examples written in python or php by different people:
https://github.com/bluetomlee/NetEase-MusicBox
http://moonlib.com/606.html
